"use client";

import { useEffect, useState } from "react";
import Link from "next/link";

type Brief = { readiness: number; items: Array<{ id: string; title: string; domain: string; instruction: string; status: string; evidenceRequired: boolean; dependencies: string[] }>; unknowns: string[]; warnings: string[] };

export default function SuccessorPage() {
  const [brief, setBrief] = useState<Brief | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { fetch("/api/successor").then(async (r) => { const data = await r.json(); if (!r.ok) throw new Error(data.error ?? "Unable to load successor brief."); setBrief(data); }).catch((e) => setError(e.message)); }, []);
  return <main className="mx-auto max-w-6xl px-6 py-12"><div className="flex items-start justify-between gap-6"><div><p className="text-sm font-medium uppercase tracking-[0.2em] text-muted-foreground">Legacy OS</p><h1 className="mt-2 text-4xl font-semibold tracking-tight">Successor Mode</h1><p className="mt-3 max-w-3xl text-muted-foreground">A successor-ready view of what needs to happen, what still needs verification, and what cannot safely be assumed.</p></div><Link href="/dashboard" className="rounded-md border px-4 py-2 text-sm">Dashboard</Link></div>{error && <p className="mt-8 rounded-lg border p-4 text-sm">{error}</p>}{brief && <><section className="mt-8 rounded-xl border p-6"><p className="text-sm text-muted-foreground">Current continuity readiness</p><div className="mt-2 text-5xl font-semibold">{brief.readiness}%</div></section><section className="mt-8"><h2 className="text-2xl font-semibold">What needs to happen</h2><div className="mt-5 space-y-3">{brief.items.map((item) => <article key={item.id} className="rounded-xl border p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-wide text-muted-foreground">{item.domain}</p><h3 className="mt-1 font-semibold">{item.title}</h3></div><span className="rounded-full border px-3 py-1 text-xs uppercase tracking-wide">{item.status}</span></div><p className="mt-3 text-sm text-muted-foreground">{item.instruction}</p>{item.evidenceRequired && <p className="mt-3 text-xs text-muted-foreground">Evidence confirmation required before this should be treated as complete.</p>}</article>)}</div></section>{brief.unknowns.length > 0 && <section className="mt-8 rounded-xl border p-6"><h2 className="text-xl font-semibold">Unknowns</h2><p className="mt-2 text-sm text-muted-foreground">These items are explicitly unknown and should not be treated as established facts.</p><ul className="mt-4 space-y-2 text-sm">{brief.unknowns.map((item) => <li key={item}>{item}</li>)}</ul></section>}{brief.warnings.length > 0 && <section className="mt-8 rounded-xl border p-6"><h2 className="text-xl font-semibold">Evidence warnings</h2><ul className="mt-4 space-y-2 text-sm text-muted-foreground">{brief.warnings.map((item) => <li key={item}>{item}</li>)}</ul></section>}</>}</main>;
}
